/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateUser = /* GraphQL */ `
  subscription OnCreateUser($filter: ModelSubscriptionUserFilterInput) {
    onCreateUser(filter: $filter) {
      id
      loginName
      userType
      idCode
      titleTh
      titleEn
      firstNameTh
      firstNameEn
      middleNameTh
      middleNameEn
      lastNameTh
      lastNameEn
      avatar
      gender
      student {
        id
        loginName
        stdId
        stdCode
        titleTh
        titleEn
        firstNameTh
        middleNameTh
        lastNameTh
        firstNameEn
        middleNameEn
        lastNameEn
        copenId
        copenNameTh
        copenNameEn
        campusCode
        campusNameTh
        campusNameEn
        facultyCode
        facultyNameTh
        facultyNameEn
        departmentCode
        departmentNameTh
        departmentNameEn
        majorCode
        majorNameTh
        majorNameEn
        nationCode
        nationalityNameTh
        nationalityNameEn
        studentStatusCode
        studentStatusNameTh
        studentStatusNameEn
        studentTypeCode
        studentTypeNameTh
        studentTypeNameEn
        edulevelCode
        edulevelNameTh
        edulevelNameEn
        studentYear
        advisorId
        advisorNameTh
        advisorNameEn
        positionTh
        email
        mobileNo
        user {
          id
          loginName
          userType
          idCode
          titleTh
          titleEn
          firstNameTh
          firstNameEn
          middleNameTh
          middleNameEn
          lastNameTh
          lastNameEn
          avatar
          gender
          student {
            id
            loginName
            stdId
            stdCode
            titleTh
            titleEn
            firstNameTh
            middleNameTh
            lastNameTh
            firstNameEn
            middleNameEn
            lastNameEn
            copenId
            copenNameTh
            copenNameEn
            campusCode
            campusNameTh
            campusNameEn
            facultyCode
            facultyNameTh
            facultyNameEn
            departmentCode
            departmentNameTh
            departmentNameEn
            majorCode
            majorNameTh
            majorNameEn
            nationCode
            nationalityNameTh
            nationalityNameEn
            studentStatusCode
            studentStatusNameTh
            studentStatusNameEn
            studentTypeCode
            studentTypeNameTh
            studentTypeNameEn
            edulevelCode
            edulevelNameTh
            edulevelNameEn
            studentYear
            advisorId
            advisorNameTh
            advisorNameEn
            positionTh
            email
            mobileNo
            createdAt
            updatedAt
            studentUserId
            __typename
          }
          loginPassword
          enrollments {
            nextToken
            __typename
          }
          createdAt
          updatedAt
          userStudentId
          __typename
        }
        createdAt
        updatedAt
        studentUserId
        __typename
      }
      loginPassword
      enrollments {
        items {
          id
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          section {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          enrollType
          createdAt
          updatedAt
          userEnrollmentsId
          subjectEnrollmentsId
          sectionEnrollmentsId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      userStudentId
      __typename
    }
  }
`;
export const onUpdateUser = /* GraphQL */ `
  subscription OnUpdateUser($filter: ModelSubscriptionUserFilterInput) {
    onUpdateUser(filter: $filter) {
      id
      loginName
      userType
      idCode
      titleTh
      titleEn
      firstNameTh
      firstNameEn
      middleNameTh
      middleNameEn
      lastNameTh
      lastNameEn
      avatar
      gender
      student {
        id
        loginName
        stdId
        stdCode
        titleTh
        titleEn
        firstNameTh
        middleNameTh
        lastNameTh
        firstNameEn
        middleNameEn
        lastNameEn
        copenId
        copenNameTh
        copenNameEn
        campusCode
        campusNameTh
        campusNameEn
        facultyCode
        facultyNameTh
        facultyNameEn
        departmentCode
        departmentNameTh
        departmentNameEn
        majorCode
        majorNameTh
        majorNameEn
        nationCode
        nationalityNameTh
        nationalityNameEn
        studentStatusCode
        studentStatusNameTh
        studentStatusNameEn
        studentTypeCode
        studentTypeNameTh
        studentTypeNameEn
        edulevelCode
        edulevelNameTh
        edulevelNameEn
        studentYear
        advisorId
        advisorNameTh
        advisorNameEn
        positionTh
        email
        mobileNo
        user {
          id
          loginName
          userType
          idCode
          titleTh
          titleEn
          firstNameTh
          firstNameEn
          middleNameTh
          middleNameEn
          lastNameTh
          lastNameEn
          avatar
          gender
          student {
            id
            loginName
            stdId
            stdCode
            titleTh
            titleEn
            firstNameTh
            middleNameTh
            lastNameTh
            firstNameEn
            middleNameEn
            lastNameEn
            copenId
            copenNameTh
            copenNameEn
            campusCode
            campusNameTh
            campusNameEn
            facultyCode
            facultyNameTh
            facultyNameEn
            departmentCode
            departmentNameTh
            departmentNameEn
            majorCode
            majorNameTh
            majorNameEn
            nationCode
            nationalityNameTh
            nationalityNameEn
            studentStatusCode
            studentStatusNameTh
            studentStatusNameEn
            studentTypeCode
            studentTypeNameTh
            studentTypeNameEn
            edulevelCode
            edulevelNameTh
            edulevelNameEn
            studentYear
            advisorId
            advisorNameTh
            advisorNameEn
            positionTh
            email
            mobileNo
            createdAt
            updatedAt
            studentUserId
            __typename
          }
          loginPassword
          enrollments {
            nextToken
            __typename
          }
          createdAt
          updatedAt
          userStudentId
          __typename
        }
        createdAt
        updatedAt
        studentUserId
        __typename
      }
      loginPassword
      enrollments {
        items {
          id
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          section {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          enrollType
          createdAt
          updatedAt
          userEnrollmentsId
          subjectEnrollmentsId
          sectionEnrollmentsId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      userStudentId
      __typename
    }
  }
`;
export const onDeleteUser = /* GraphQL */ `
  subscription OnDeleteUser($filter: ModelSubscriptionUserFilterInput) {
    onDeleteUser(filter: $filter) {
      id
      loginName
      userType
      idCode
      titleTh
      titleEn
      firstNameTh
      firstNameEn
      middleNameTh
      middleNameEn
      lastNameTh
      lastNameEn
      avatar
      gender
      student {
        id
        loginName
        stdId
        stdCode
        titleTh
        titleEn
        firstNameTh
        middleNameTh
        lastNameTh
        firstNameEn
        middleNameEn
        lastNameEn
        copenId
        copenNameTh
        copenNameEn
        campusCode
        campusNameTh
        campusNameEn
        facultyCode
        facultyNameTh
        facultyNameEn
        departmentCode
        departmentNameTh
        departmentNameEn
        majorCode
        majorNameTh
        majorNameEn
        nationCode
        nationalityNameTh
        nationalityNameEn
        studentStatusCode
        studentStatusNameTh
        studentStatusNameEn
        studentTypeCode
        studentTypeNameTh
        studentTypeNameEn
        edulevelCode
        edulevelNameTh
        edulevelNameEn
        studentYear
        advisorId
        advisorNameTh
        advisorNameEn
        positionTh
        email
        mobileNo
        user {
          id
          loginName
          userType
          idCode
          titleTh
          titleEn
          firstNameTh
          firstNameEn
          middleNameTh
          middleNameEn
          lastNameTh
          lastNameEn
          avatar
          gender
          student {
            id
            loginName
            stdId
            stdCode
            titleTh
            titleEn
            firstNameTh
            middleNameTh
            lastNameTh
            firstNameEn
            middleNameEn
            lastNameEn
            copenId
            copenNameTh
            copenNameEn
            campusCode
            campusNameTh
            campusNameEn
            facultyCode
            facultyNameTh
            facultyNameEn
            departmentCode
            departmentNameTh
            departmentNameEn
            majorCode
            majorNameTh
            majorNameEn
            nationCode
            nationalityNameTh
            nationalityNameEn
            studentStatusCode
            studentStatusNameTh
            studentStatusNameEn
            studentTypeCode
            studentTypeNameTh
            studentTypeNameEn
            edulevelCode
            edulevelNameTh
            edulevelNameEn
            studentYear
            advisorId
            advisorNameTh
            advisorNameEn
            positionTh
            email
            mobileNo
            createdAt
            updatedAt
            studentUserId
            __typename
          }
          loginPassword
          enrollments {
            nextToken
            __typename
          }
          createdAt
          updatedAt
          userStudentId
          __typename
        }
        createdAt
        updatedAt
        studentUserId
        __typename
      }
      loginPassword
      enrollments {
        items {
          id
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          section {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          enrollType
          createdAt
          updatedAt
          userEnrollmentsId
          subjectEnrollmentsId
          sectionEnrollmentsId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      userStudentId
      __typename
    }
  }
`;
export const onCreateStudent = /* GraphQL */ `
  subscription OnCreateStudent($filter: ModelSubscriptionStudentFilterInput) {
    onCreateStudent(filter: $filter) {
      id
      loginName
      stdId
      stdCode
      titleTh
      titleEn
      firstNameTh
      middleNameTh
      lastNameTh
      firstNameEn
      middleNameEn
      lastNameEn
      copenId
      copenNameTh
      copenNameEn
      campusCode
      campusNameTh
      campusNameEn
      facultyCode
      facultyNameTh
      facultyNameEn
      departmentCode
      departmentNameTh
      departmentNameEn
      majorCode
      majorNameTh
      majorNameEn
      nationCode
      nationalityNameTh
      nationalityNameEn
      studentStatusCode
      studentStatusNameTh
      studentStatusNameEn
      studentTypeCode
      studentTypeNameTh
      studentTypeNameEn
      edulevelCode
      edulevelNameTh
      edulevelNameEn
      studentYear
      advisorId
      advisorNameTh
      advisorNameEn
      positionTh
      email
      mobileNo
      user {
        id
        loginName
        userType
        idCode
        titleTh
        titleEn
        firstNameTh
        firstNameEn
        middleNameTh
        middleNameEn
        lastNameTh
        lastNameEn
        avatar
        gender
        student {
          id
          loginName
          stdId
          stdCode
          titleTh
          titleEn
          firstNameTh
          middleNameTh
          lastNameTh
          firstNameEn
          middleNameEn
          lastNameEn
          copenId
          copenNameTh
          copenNameEn
          campusCode
          campusNameTh
          campusNameEn
          facultyCode
          facultyNameTh
          facultyNameEn
          departmentCode
          departmentNameTh
          departmentNameEn
          majorCode
          majorNameTh
          majorNameEn
          nationCode
          nationalityNameTh
          nationalityNameEn
          studentStatusCode
          studentStatusNameTh
          studentStatusNameEn
          studentTypeCode
          studentTypeNameTh
          studentTypeNameEn
          edulevelCode
          edulevelNameTh
          edulevelNameEn
          studentYear
          advisorId
          advisorNameTh
          advisorNameEn
          positionTh
          email
          mobileNo
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          createdAt
          updatedAt
          studentUserId
          __typename
        }
        loginPassword
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        userStudentId
        __typename
      }
      createdAt
      updatedAt
      studentUserId
      __typename
    }
  }
`;
export const onUpdateStudent = /* GraphQL */ `
  subscription OnUpdateStudent($filter: ModelSubscriptionStudentFilterInput) {
    onUpdateStudent(filter: $filter) {
      id
      loginName
      stdId
      stdCode
      titleTh
      titleEn
      firstNameTh
      middleNameTh
      lastNameTh
      firstNameEn
      middleNameEn
      lastNameEn
      copenId
      copenNameTh
      copenNameEn
      campusCode
      campusNameTh
      campusNameEn
      facultyCode
      facultyNameTh
      facultyNameEn
      departmentCode
      departmentNameTh
      departmentNameEn
      majorCode
      majorNameTh
      majorNameEn
      nationCode
      nationalityNameTh
      nationalityNameEn
      studentStatusCode
      studentStatusNameTh
      studentStatusNameEn
      studentTypeCode
      studentTypeNameTh
      studentTypeNameEn
      edulevelCode
      edulevelNameTh
      edulevelNameEn
      studentYear
      advisorId
      advisorNameTh
      advisorNameEn
      positionTh
      email
      mobileNo
      user {
        id
        loginName
        userType
        idCode
        titleTh
        titleEn
        firstNameTh
        firstNameEn
        middleNameTh
        middleNameEn
        lastNameTh
        lastNameEn
        avatar
        gender
        student {
          id
          loginName
          stdId
          stdCode
          titleTh
          titleEn
          firstNameTh
          middleNameTh
          lastNameTh
          firstNameEn
          middleNameEn
          lastNameEn
          copenId
          copenNameTh
          copenNameEn
          campusCode
          campusNameTh
          campusNameEn
          facultyCode
          facultyNameTh
          facultyNameEn
          departmentCode
          departmentNameTh
          departmentNameEn
          majorCode
          majorNameTh
          majorNameEn
          nationCode
          nationalityNameTh
          nationalityNameEn
          studentStatusCode
          studentStatusNameTh
          studentStatusNameEn
          studentTypeCode
          studentTypeNameTh
          studentTypeNameEn
          edulevelCode
          edulevelNameTh
          edulevelNameEn
          studentYear
          advisorId
          advisorNameTh
          advisorNameEn
          positionTh
          email
          mobileNo
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          createdAt
          updatedAt
          studentUserId
          __typename
        }
        loginPassword
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        userStudentId
        __typename
      }
      createdAt
      updatedAt
      studentUserId
      __typename
    }
  }
`;
export const onDeleteStudent = /* GraphQL */ `
  subscription OnDeleteStudent($filter: ModelSubscriptionStudentFilterInput) {
    onDeleteStudent(filter: $filter) {
      id
      loginName
      stdId
      stdCode
      titleTh
      titleEn
      firstNameTh
      middleNameTh
      lastNameTh
      firstNameEn
      middleNameEn
      lastNameEn
      copenId
      copenNameTh
      copenNameEn
      campusCode
      campusNameTh
      campusNameEn
      facultyCode
      facultyNameTh
      facultyNameEn
      departmentCode
      departmentNameTh
      departmentNameEn
      majorCode
      majorNameTh
      majorNameEn
      nationCode
      nationalityNameTh
      nationalityNameEn
      studentStatusCode
      studentStatusNameTh
      studentStatusNameEn
      studentTypeCode
      studentTypeNameTh
      studentTypeNameEn
      edulevelCode
      edulevelNameTh
      edulevelNameEn
      studentYear
      advisorId
      advisorNameTh
      advisorNameEn
      positionTh
      email
      mobileNo
      user {
        id
        loginName
        userType
        idCode
        titleTh
        titleEn
        firstNameTh
        firstNameEn
        middleNameTh
        middleNameEn
        lastNameTh
        lastNameEn
        avatar
        gender
        student {
          id
          loginName
          stdId
          stdCode
          titleTh
          titleEn
          firstNameTh
          middleNameTh
          lastNameTh
          firstNameEn
          middleNameEn
          lastNameEn
          copenId
          copenNameTh
          copenNameEn
          campusCode
          campusNameTh
          campusNameEn
          facultyCode
          facultyNameTh
          facultyNameEn
          departmentCode
          departmentNameTh
          departmentNameEn
          majorCode
          majorNameTh
          majorNameEn
          nationCode
          nationalityNameTh
          nationalityNameEn
          studentStatusCode
          studentStatusNameTh
          studentStatusNameEn
          studentTypeCode
          studentTypeNameTh
          studentTypeNameEn
          edulevelCode
          edulevelNameTh
          edulevelNameEn
          studentYear
          advisorId
          advisorNameTh
          advisorNameEn
          positionTh
          email
          mobileNo
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          createdAt
          updatedAt
          studentUserId
          __typename
        }
        loginPassword
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        userStudentId
        __typename
      }
      createdAt
      updatedAt
      studentUserId
      __typename
    }
  }
`;
export const onCreateSubject = /* GraphQL */ `
  subscription OnCreateSubject($filter: ModelSubscriptionSubjectFilterInput) {
    onCreateSubject(filter: $filter) {
      id
      subjectCode
      subjectNameTh
      subjectNameEn
      credit
      theoryHour
      practiceHour
      selfHour
      subjectType
      flagCur
      creditShow
      relateSubjectCode
      sections {
        items {
          id
          academicYear
          semester
          campusCode
          sectionId
          subjectCode
          flagRegisCon
          subjectNameTh
          subjectNameEn
          maxCredit
          sectionCode
          sectionType
          sectionTypeTh
          sectionTypeEn
          studentStatusCode
          stdStatusTh
          stdStatusEn
          coursedate
          coursedateth
          coursedateen
          totalSeat
          totalRegistered
          teacherName
          teacherNameEn
          roomNameTh
          roomNameEn
          property
          nonProperty
          midternDate
          finalDate
          sectionStatus
          relateSubjectCode
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          enrollments {
            nextToken
            __typename
          }
          createdAt
          updatedAt
          subjectSectionsId
          __typename
        }
        nextToken
        __typename
      }
      enrollments {
        items {
          id
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          section {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          enrollType
          createdAt
          updatedAt
          userEnrollmentsId
          subjectEnrollmentsId
          sectionEnrollmentsId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateSubject = /* GraphQL */ `
  subscription OnUpdateSubject($filter: ModelSubscriptionSubjectFilterInput) {
    onUpdateSubject(filter: $filter) {
      id
      subjectCode
      subjectNameTh
      subjectNameEn
      credit
      theoryHour
      practiceHour
      selfHour
      subjectType
      flagCur
      creditShow
      relateSubjectCode
      sections {
        items {
          id
          academicYear
          semester
          campusCode
          sectionId
          subjectCode
          flagRegisCon
          subjectNameTh
          subjectNameEn
          maxCredit
          sectionCode
          sectionType
          sectionTypeTh
          sectionTypeEn
          studentStatusCode
          stdStatusTh
          stdStatusEn
          coursedate
          coursedateth
          coursedateen
          totalSeat
          totalRegistered
          teacherName
          teacherNameEn
          roomNameTh
          roomNameEn
          property
          nonProperty
          midternDate
          finalDate
          sectionStatus
          relateSubjectCode
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          enrollments {
            nextToken
            __typename
          }
          createdAt
          updatedAt
          subjectSectionsId
          __typename
        }
        nextToken
        __typename
      }
      enrollments {
        items {
          id
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          section {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          enrollType
          createdAt
          updatedAt
          userEnrollmentsId
          subjectEnrollmentsId
          sectionEnrollmentsId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteSubject = /* GraphQL */ `
  subscription OnDeleteSubject($filter: ModelSubscriptionSubjectFilterInput) {
    onDeleteSubject(filter: $filter) {
      id
      subjectCode
      subjectNameTh
      subjectNameEn
      credit
      theoryHour
      practiceHour
      selfHour
      subjectType
      flagCur
      creditShow
      relateSubjectCode
      sections {
        items {
          id
          academicYear
          semester
          campusCode
          sectionId
          subjectCode
          flagRegisCon
          subjectNameTh
          subjectNameEn
          maxCredit
          sectionCode
          sectionType
          sectionTypeTh
          sectionTypeEn
          studentStatusCode
          stdStatusTh
          stdStatusEn
          coursedate
          coursedateth
          coursedateen
          totalSeat
          totalRegistered
          teacherName
          teacherNameEn
          roomNameTh
          roomNameEn
          property
          nonProperty
          midternDate
          finalDate
          sectionStatus
          relateSubjectCode
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          enrollments {
            nextToken
            __typename
          }
          createdAt
          updatedAt
          subjectSectionsId
          __typename
        }
        nextToken
        __typename
      }
      enrollments {
        items {
          id
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          section {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          enrollType
          createdAt
          updatedAt
          userEnrollmentsId
          subjectEnrollmentsId
          sectionEnrollmentsId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateSection = /* GraphQL */ `
  subscription OnCreateSection($filter: ModelSubscriptionSectionFilterInput) {
    onCreateSection(filter: $filter) {
      id
      academicYear
      semester
      campusCode
      sectionId
      subjectCode
      flagRegisCon
      subjectNameTh
      subjectNameEn
      maxCredit
      sectionCode
      sectionType
      sectionTypeTh
      sectionTypeEn
      studentStatusCode
      stdStatusTh
      stdStatusEn
      coursedate
      coursedateth
      coursedateen
      totalSeat
      totalRegistered
      teacherName
      teacherNameEn
      roomNameTh
      roomNameEn
      property
      nonProperty
      midternDate
      finalDate
      sectionStatus
      relateSubjectCode
      subject {
        id
        subjectCode
        subjectNameTh
        subjectNameEn
        credit
        theoryHour
        practiceHour
        selfHour
        subjectType
        flagCur
        creditShow
        relateSubjectCode
        sections {
          items {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          nextToken
          __typename
        }
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        __typename
      }
      enrollments {
        items {
          id
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          section {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          enrollType
          createdAt
          updatedAt
          userEnrollmentsId
          subjectEnrollmentsId
          sectionEnrollmentsId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      subjectSectionsId
      __typename
    }
  }
`;
export const onUpdateSection = /* GraphQL */ `
  subscription OnUpdateSection($filter: ModelSubscriptionSectionFilterInput) {
    onUpdateSection(filter: $filter) {
      id
      academicYear
      semester
      campusCode
      sectionId
      subjectCode
      flagRegisCon
      subjectNameTh
      subjectNameEn
      maxCredit
      sectionCode
      sectionType
      sectionTypeTh
      sectionTypeEn
      studentStatusCode
      stdStatusTh
      stdStatusEn
      coursedate
      coursedateth
      coursedateen
      totalSeat
      totalRegistered
      teacherName
      teacherNameEn
      roomNameTh
      roomNameEn
      property
      nonProperty
      midternDate
      finalDate
      sectionStatus
      relateSubjectCode
      subject {
        id
        subjectCode
        subjectNameTh
        subjectNameEn
        credit
        theoryHour
        practiceHour
        selfHour
        subjectType
        flagCur
        creditShow
        relateSubjectCode
        sections {
          items {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          nextToken
          __typename
        }
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        __typename
      }
      enrollments {
        items {
          id
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          section {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          enrollType
          createdAt
          updatedAt
          userEnrollmentsId
          subjectEnrollmentsId
          sectionEnrollmentsId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      subjectSectionsId
      __typename
    }
  }
`;
export const onDeleteSection = /* GraphQL */ `
  subscription OnDeleteSection($filter: ModelSubscriptionSectionFilterInput) {
    onDeleteSection(filter: $filter) {
      id
      academicYear
      semester
      campusCode
      sectionId
      subjectCode
      flagRegisCon
      subjectNameTh
      subjectNameEn
      maxCredit
      sectionCode
      sectionType
      sectionTypeTh
      sectionTypeEn
      studentStatusCode
      stdStatusTh
      stdStatusEn
      coursedate
      coursedateth
      coursedateen
      totalSeat
      totalRegistered
      teacherName
      teacherNameEn
      roomNameTh
      roomNameEn
      property
      nonProperty
      midternDate
      finalDate
      sectionStatus
      relateSubjectCode
      subject {
        id
        subjectCode
        subjectNameTh
        subjectNameEn
        credit
        theoryHour
        practiceHour
        selfHour
        subjectType
        flagCur
        creditShow
        relateSubjectCode
        sections {
          items {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          nextToken
          __typename
        }
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        __typename
      }
      enrollments {
        items {
          id
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          subject {
            id
            subjectCode
            subjectNameTh
            subjectNameEn
            credit
            theoryHour
            practiceHour
            selfHour
            subjectType
            flagCur
            creditShow
            relateSubjectCode
            createdAt
            updatedAt
            __typename
          }
          section {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          enrollType
          createdAt
          updatedAt
          userEnrollmentsId
          subjectEnrollmentsId
          sectionEnrollmentsId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      subjectSectionsId
      __typename
    }
  }
`;
export const onCreateEnrollment = /* GraphQL */ `
  subscription OnCreateEnrollment(
    $filter: ModelSubscriptionEnrollmentFilterInput
  ) {
    onCreateEnrollment(filter: $filter) {
      id
      user {
        id
        loginName
        userType
        idCode
        titleTh
        titleEn
        firstNameTh
        firstNameEn
        middleNameTh
        middleNameEn
        lastNameTh
        lastNameEn
        avatar
        gender
        student {
          id
          loginName
          stdId
          stdCode
          titleTh
          titleEn
          firstNameTh
          middleNameTh
          lastNameTh
          firstNameEn
          middleNameEn
          lastNameEn
          copenId
          copenNameTh
          copenNameEn
          campusCode
          campusNameTh
          campusNameEn
          facultyCode
          facultyNameTh
          facultyNameEn
          departmentCode
          departmentNameTh
          departmentNameEn
          majorCode
          majorNameTh
          majorNameEn
          nationCode
          nationalityNameTh
          nationalityNameEn
          studentStatusCode
          studentStatusNameTh
          studentStatusNameEn
          studentTypeCode
          studentTypeNameTh
          studentTypeNameEn
          edulevelCode
          edulevelNameTh
          edulevelNameEn
          studentYear
          advisorId
          advisorNameTh
          advisorNameEn
          positionTh
          email
          mobileNo
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          createdAt
          updatedAt
          studentUserId
          __typename
        }
        loginPassword
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        userStudentId
        __typename
      }
      subject {
        id
        subjectCode
        subjectNameTh
        subjectNameEn
        credit
        theoryHour
        practiceHour
        selfHour
        subjectType
        flagCur
        creditShow
        relateSubjectCode
        sections {
          items {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          nextToken
          __typename
        }
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        __typename
      }
      section {
        id
        academicYear
        semester
        campusCode
        sectionId
        subjectCode
        flagRegisCon
        subjectNameTh
        subjectNameEn
        maxCredit
        sectionCode
        sectionType
        sectionTypeTh
        sectionTypeEn
        studentStatusCode
        stdStatusTh
        stdStatusEn
        coursedate
        coursedateth
        coursedateen
        totalSeat
        totalRegistered
        teacherName
        teacherNameEn
        roomNameTh
        roomNameEn
        property
        nonProperty
        midternDate
        finalDate
        sectionStatus
        relateSubjectCode
        subject {
          id
          subjectCode
          subjectNameTh
          subjectNameEn
          credit
          theoryHour
          practiceHour
          selfHour
          subjectType
          flagCur
          creditShow
          relateSubjectCode
          sections {
            nextToken
            __typename
          }
          enrollments {
            nextToken
            __typename
          }
          createdAt
          updatedAt
          __typename
        }
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        subjectSectionsId
        __typename
      }
      enrollType
      createdAt
      updatedAt
      userEnrollmentsId
      subjectEnrollmentsId
      sectionEnrollmentsId
      __typename
    }
  }
`;
export const onUpdateEnrollment = /* GraphQL */ `
  subscription OnUpdateEnrollment(
    $filter: ModelSubscriptionEnrollmentFilterInput
  ) {
    onUpdateEnrollment(filter: $filter) {
      id
      user {
        id
        loginName
        userType
        idCode
        titleTh
        titleEn
        firstNameTh
        firstNameEn
        middleNameTh
        middleNameEn
        lastNameTh
        lastNameEn
        avatar
        gender
        student {
          id
          loginName
          stdId
          stdCode
          titleTh
          titleEn
          firstNameTh
          middleNameTh
          lastNameTh
          firstNameEn
          middleNameEn
          lastNameEn
          copenId
          copenNameTh
          copenNameEn
          campusCode
          campusNameTh
          campusNameEn
          facultyCode
          facultyNameTh
          facultyNameEn
          departmentCode
          departmentNameTh
          departmentNameEn
          majorCode
          majorNameTh
          majorNameEn
          nationCode
          nationalityNameTh
          nationalityNameEn
          studentStatusCode
          studentStatusNameTh
          studentStatusNameEn
          studentTypeCode
          studentTypeNameTh
          studentTypeNameEn
          edulevelCode
          edulevelNameTh
          edulevelNameEn
          studentYear
          advisorId
          advisorNameTh
          advisorNameEn
          positionTh
          email
          mobileNo
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          createdAt
          updatedAt
          studentUserId
          __typename
        }
        loginPassword
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        userStudentId
        __typename
      }
      subject {
        id
        subjectCode
        subjectNameTh
        subjectNameEn
        credit
        theoryHour
        practiceHour
        selfHour
        subjectType
        flagCur
        creditShow
        relateSubjectCode
        sections {
          items {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          nextToken
          __typename
        }
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        __typename
      }
      section {
        id
        academicYear
        semester
        campusCode
        sectionId
        subjectCode
        flagRegisCon
        subjectNameTh
        subjectNameEn
        maxCredit
        sectionCode
        sectionType
        sectionTypeTh
        sectionTypeEn
        studentStatusCode
        stdStatusTh
        stdStatusEn
        coursedate
        coursedateth
        coursedateen
        totalSeat
        totalRegistered
        teacherName
        teacherNameEn
        roomNameTh
        roomNameEn
        property
        nonProperty
        midternDate
        finalDate
        sectionStatus
        relateSubjectCode
        subject {
          id
          subjectCode
          subjectNameTh
          subjectNameEn
          credit
          theoryHour
          practiceHour
          selfHour
          subjectType
          flagCur
          creditShow
          relateSubjectCode
          sections {
            nextToken
            __typename
          }
          enrollments {
            nextToken
            __typename
          }
          createdAt
          updatedAt
          __typename
        }
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        subjectSectionsId
        __typename
      }
      enrollType
      createdAt
      updatedAt
      userEnrollmentsId
      subjectEnrollmentsId
      sectionEnrollmentsId
      __typename
    }
  }
`;
export const onDeleteEnrollment = /* GraphQL */ `
  subscription OnDeleteEnrollment(
    $filter: ModelSubscriptionEnrollmentFilterInput
  ) {
    onDeleteEnrollment(filter: $filter) {
      id
      user {
        id
        loginName
        userType
        idCode
        titleTh
        titleEn
        firstNameTh
        firstNameEn
        middleNameTh
        middleNameEn
        lastNameTh
        lastNameEn
        avatar
        gender
        student {
          id
          loginName
          stdId
          stdCode
          titleTh
          titleEn
          firstNameTh
          middleNameTh
          lastNameTh
          firstNameEn
          middleNameEn
          lastNameEn
          copenId
          copenNameTh
          copenNameEn
          campusCode
          campusNameTh
          campusNameEn
          facultyCode
          facultyNameTh
          facultyNameEn
          departmentCode
          departmentNameTh
          departmentNameEn
          majorCode
          majorNameTh
          majorNameEn
          nationCode
          nationalityNameTh
          nationalityNameEn
          studentStatusCode
          studentStatusNameTh
          studentStatusNameEn
          studentTypeCode
          studentTypeNameTh
          studentTypeNameEn
          edulevelCode
          edulevelNameTh
          edulevelNameEn
          studentYear
          advisorId
          advisorNameTh
          advisorNameEn
          positionTh
          email
          mobileNo
          user {
            id
            loginName
            userType
            idCode
            titleTh
            titleEn
            firstNameTh
            firstNameEn
            middleNameTh
            middleNameEn
            lastNameTh
            lastNameEn
            avatar
            gender
            loginPassword
            createdAt
            updatedAt
            userStudentId
            __typename
          }
          createdAt
          updatedAt
          studentUserId
          __typename
        }
        loginPassword
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        userStudentId
        __typename
      }
      subject {
        id
        subjectCode
        subjectNameTh
        subjectNameEn
        credit
        theoryHour
        practiceHour
        selfHour
        subjectType
        flagCur
        creditShow
        relateSubjectCode
        sections {
          items {
            id
            academicYear
            semester
            campusCode
            sectionId
            subjectCode
            flagRegisCon
            subjectNameTh
            subjectNameEn
            maxCredit
            sectionCode
            sectionType
            sectionTypeTh
            sectionTypeEn
            studentStatusCode
            stdStatusTh
            stdStatusEn
            coursedate
            coursedateth
            coursedateen
            totalSeat
            totalRegistered
            teacherName
            teacherNameEn
            roomNameTh
            roomNameEn
            property
            nonProperty
            midternDate
            finalDate
            sectionStatus
            relateSubjectCode
            createdAt
            updatedAt
            subjectSectionsId
            __typename
          }
          nextToken
          __typename
        }
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        __typename
      }
      section {
        id
        academicYear
        semester
        campusCode
        sectionId
        subjectCode
        flagRegisCon
        subjectNameTh
        subjectNameEn
        maxCredit
        sectionCode
        sectionType
        sectionTypeTh
        sectionTypeEn
        studentStatusCode
        stdStatusTh
        stdStatusEn
        coursedate
        coursedateth
        coursedateen
        totalSeat
        totalRegistered
        teacherName
        teacherNameEn
        roomNameTh
        roomNameEn
        property
        nonProperty
        midternDate
        finalDate
        sectionStatus
        relateSubjectCode
        subject {
          id
          subjectCode
          subjectNameTh
          subjectNameEn
          credit
          theoryHour
          practiceHour
          selfHour
          subjectType
          flagCur
          creditShow
          relateSubjectCode
          sections {
            nextToken
            __typename
          }
          enrollments {
            nextToken
            __typename
          }
          createdAt
          updatedAt
          __typename
        }
        enrollments {
          items {
            id
            enrollType
            createdAt
            updatedAt
            userEnrollmentsId
            subjectEnrollmentsId
            sectionEnrollmentsId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        subjectSectionsId
        __typename
      }
      enrollType
      createdAt
      updatedAt
      userEnrollmentsId
      subjectEnrollmentsId
      sectionEnrollmentsId
      __typename
    }
  }
`;
